[package]
name = "zeroing_memory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zeroize = "1.7.0"

[profile.dev]
opt-level = 3
